using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Text;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Timekeeper.Ai;
using Timekeeper.App.Settings;
using Timekeeper.Core;
using Timekeeper.Core.Timesheets;

namespace Timekeeper.App.ViewModels;

/// <summary>The day's draft timesheet: generated by AI from the activity log, then edited by hand.</summary>
public sealed partial class TimesheetPageViewModel : PageViewModel
{
    private readonly ITimesheetStore _timesheets;
    private readonly IActivityStore _activity;
    private readonly HttpClient _http;
    private readonly Func<AppSettings> _settings;
    private CancellationTokenSource? _generation;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowEmptyState))]
    [NotifyCanExecuteChangedFor(nameof(GenerateCommand))]
    private bool _isGenerating;

    [ObservableProperty]
    private double _progress;

    [ObservableProperty]
    private string _progressText = "";

    [ObservableProperty]
    private string? _error;

    [ObservableProperty]
    private string _total = "0,00 h";

    [ObservableProperty]
    private bool _justCopied;

    public TimesheetPageViewModel(
        ITimesheetStore timesheets,
        IActivityStore activity,
        HttpClient http,
        Func<AppSettings> settings,
        DaySelection day)
        : base("Tidslogg", "")
    {
        _timesheets = timesheets;
        _activity = activity;
        _http = http;
        _settings = settings;
        Day = day;
        Day.PropertyChanged += OnDayChanged;
        Entries.CollectionChanged += (_, _) => OnEntriesChanged();
        Load();
    }

    public DaySelection Day { get; }

    public ObservableCollection<TimesheetEntryViewModel> Entries { get; } = [];

    public IReadOnlyList<string> ClientNames { get; private set; } = [];

    public IReadOnlyList<string> Activities => _settings().Activities.Append(TimesheetBuilder.InternalLabel).ToList();

    public bool HasEntries => Entries.Count > 0;

    public bool ShowEmptyState => !HasEntries && !IsGenerating;

    public bool HasError => Error is not null;

    /// <summary>Which models will be used, so it is clear why results may be rough.</summary>
    public string ModelStatus
    {
        get
        {
            var settings = _settings();
            var models = new[]
            {
                settings.JevApiKey.Length > 0 ? "Jev" : null,
                settings.OpenAiApiKey.Length > 0 ? "Luna" : null,
            }.OfType<string>().ToList();
            return models.Count == 0
                ? "Inga API-nycklar inlagda: bara kundnamn i fönstertitlar känns igen."
                : $"Klassificeras med {string.Join(" och ", models)}.";
        }
    }

    public override void OnActivated()
    {
        ClientNames = _timesheets.GetClients().Select(c => c.Name).Append(TimesheetBuilder.InternalLabel).ToList();
        OnPropertyChanged(nameof(ClientNames));
        OnPropertyChanged(nameof(Activities));
        OnPropertyChanged(nameof(ModelStatus));
    }

    [RelayCommand(CanExecute = nameof(CanGenerate))]
    private async Task GenerateAsync()
    {
        IsGenerating = true;
        Error = null;
        Progress = 0;
        ProgressText = "Läser dagens aktivitet";
        _generation = new CancellationTokenSource();
        var token = _generation.Token;
        var date = Day.Day;

        try
        {
            var settings = _settings();
            var evidence = GatherEvidence();
            var clients = _timesheets.GetClients();
            var builder = new TimesheetBuilder(
                settings.ToTimesheetOptions(),
                settings.JevApiKey.Length > 0 ? new JevDecisionModel(_http, settings.JevApiKey, settings.JevModel) : null,
                settings.OpenAiApiKey.Length > 0 ? new LunaLanguageModel(_http, settings.OpenAiApiKey, settings.LunaModel) : null);

            var progress = new Progress<TimesheetProgress>(p =>
            {
                Progress = p.Total == 0 ? 0 : 100.0 * p.Done / p.Total;
                ProgressText = p.Total == 0 ? p.Message : $"{p.Message} ({p.Done} av {p.Total})";
            });
            var entries = await Task.Run(() => builder.BuildAsync(date, evidence, clients, progress, token), token);

            _timesheets.ReplaceEntries(date, entries);
            if (Day.Day == date)
            {
                Load();
            }
        }
        catch (OperationCanceledException) when (token.IsCancellationRequested)
        {
        }
        catch (Exception ex)
        {
            // This is the boundary to the UI: show the problem rather than crash the tracker.
            Error = ex is AiServiceException or HttpRequestException ? ex.Message : $"Något gick fel: {ex.Message}";
        }
        finally
        {
            _generation.Dispose();
            _generation = null;
            IsGenerating = false;
        }
    }

    [RelayCommand]
    private void Cancel() => _generation?.Cancel();

    [RelayCommand]
    private void AddEntry()
    {
        var entry = new TimesheetEntry
        {
            Date = Day.Day,
            Client = "",
            Activity = _settings().DefaultActivity,
            Minutes = _settings().RoundingMinutes,
        };
        _timesheets.SaveEntry(entry);
        Entries.Add(Wrap(entry));
    }

    [RelayCommand]
    private void DeleteEntry(TimesheetEntryViewModel entry)
    {
        _timesheets.DeleteEntry(entry.Entry.Id);
        Entries.Remove(entry);
    }

    [RelayCommand]
    private void DismissError() => Error = null;

    /// <summary>Tab-separated rows (client, activity, hours, comment) that paste into spreadsheets and most time systems.</summary>
    public string BuildClipboardText()
    {
        var text = new StringBuilder();
        foreach (var entry in Entries.Where(e => e.Client != TimesheetBuilder.InternalLabel))
        {
            text.AppendLine(string.Join('\t', entry.Client, entry.Activity, Format.Hours(entry.Hours ?? 0), entry.Comment));
        }

        return text.ToString();
    }

    public async Task ShowCopiedAsync()
    {
        JustCopied = true;
        await Task.Delay(TimeSpan.FromSeconds(2));
        JustCopied = false;
    }

    partial void OnErrorChanged(string? value) => OnPropertyChanged(nameof(HasError));

    private bool CanGenerate() => !IsGenerating;

    private IReadOnlyList<SegmentEvidence> GatherEvidence()
    {
        var firstScreenshots = _activity.GetScreenshots(Day.StartUtc, Day.EndUtc)
            .GroupBy(s => s.SegmentId)
            .ToDictionary(g => g.Key, g => g.First());

        return _activity.GetSegments(Day.StartUtc, Day.EndUtc)
            .Where(s => !string.Equals(s.ProcessName, "Timekeeper", StringComparison.OrdinalIgnoreCase))
            .Select(s =>
            {
                firstScreenshots.TryGetValue(s.Id, out var screenshot);
                return new SegmentEvidence(s, screenshot?.OcrText, screenshot?.FilePath);
            })
            .ToList();
    }

    private void OnDayChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(DaySelection.Date))
        {
            Error = null;
            Load();
        }
    }

    private void Load()
    {
        Entries.Clear();
        foreach (var entry in _timesheets.GetEntries(Day.Day))
        {
            Entries.Add(Wrap(entry));
        }
    }

    private TimesheetEntryViewModel Wrap(TimesheetEntry entry) =>
        new(entry, _settings().ConfidenceThreshold, Save);

    private void Save(TimesheetEntryViewModel entry)
    {
        _timesheets.SaveEntry(entry.Entry);
        UpdateTotal();
    }

    private void OnEntriesChanged()
    {
        OnPropertyChanged(nameof(HasEntries));
        OnPropertyChanged(nameof(ShowEmptyState));
        UpdateTotal();
    }

    private void UpdateTotal() =>
        Total = $"{Format.Hours(Entries.Where(e => e.Client != TimesheetBuilder.InternalLabel).Sum(e => e.Hours ?? 0))} h";
}
