using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Text;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Timekeeper.Ai;
using Timekeeper.App.Settings;
using Timekeeper.Core;
using Timekeeper.Core.Timesheets;

namespace Timekeeper.App.ViewModels;

/// <summary>A row of the preliminary timesheet, as shown.</summary>
/// <param name="IsDimmed">Not yet classified, or not work: shown, but not part of the timesheet as is.</param>
public sealed record PreviewRow(string Client, string Hours, string TimeSpent, string Summary, bool IsUncertain, bool IsDimmed);

/// <summary>
/// The day's timesheet. Until a draft is created it shows a preliminary timesheet that follows the
/// day as it happens; the draft is generated by AI from the activity log, then edited by hand.
/// </summary>
public sealed partial class TimesheetPageViewModel : PageViewModel
{
    private readonly ITimesheetStore _timesheets;
    private readonly IActivityStore _activity;
    private readonly ILabelStore _labels;
    private readonly HttpClient _http;
    private readonly Func<AppSettings> _settings;
    private CancellationTokenSource? _generation;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowEmptyState), nameof(ShowPreview))]
    [NotifyCanExecuteChangedFor(nameof(GenerateCommand))]
    private bool _isGenerating;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasPreview), nameof(ShowEmptyState), nameof(ShowPreview))]
    private IReadOnlyList<PreviewRow> _preview = [];

    [ObservableProperty]
    private string _previewTotal = "";

    /// <summary>Recorded time not yet in the saved draft, e.g. "1 h 05 min". Null when the draft is current.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasNewTime))]
    private string? _newTime;

    [ObservableProperty]
    private double _progress;

    [ObservableProperty]
    private string _progressText = "";

    [ObservableProperty]
    private string? _error;

    [ObservableProperty]
    private string _total = "0,00 h";

    [ObservableProperty]
    private bool _justCopied;

    public TimesheetPageViewModel(
        ITimesheetStore timesheets,
        IActivityStore activity,
        ILabelStore labels,
        HttpClient http,
        Func<AppSettings> settings,
        DaySelection day)
        : base("Tidslogg", "")
    {
        _timesheets = timesheets;
        _activity = activity;
        _labels = labels;
        _http = http;
        _settings = settings;
        Day = day;
        Day.PropertyChanged += OnDayChanged;
        Entries.CollectionChanged += (_, _) => OnEntriesChanged();
        Load();
    }

    public DaySelection Day { get; }

    public ObservableCollection<TimesheetEntryViewModel> Entries { get; } = [];

    public IReadOnlyList<string> ClientNames { get; private set; } = [];

    public IReadOnlyList<string> Activities => _settings().Activities.Append(TimesheetBuilder.InternalLabel).ToList();

    public bool HasEntries => Entries.Count > 0;

    public bool HasPreview => Preview.Count > 0;

    public bool ShowPreview => !HasEntries && !IsGenerating && HasPreview;

    public bool ShowEmptyState => !HasEntries && !IsGenerating && !HasPreview;

    public bool HasNewTime => NewTime is not null;

    public bool HasError => Error is not null;

    /// <summary>Which models will be used, so it is clear why results may be rough.</summary>
    public string ModelStatus
    {
        get
        {
            var settings = _settings();
            var models = new[]
            {
                settings.JevApiKey.Length > 0 ? "Jev" : null,
                settings.OpenAiApiKey.Length > 0 ? "Luna" : null,
            }.OfType<string>().ToList();
            return models.Count == 0
                ? "Inga API-nycklar inlagda: bara kundnamn i fönstertitlar känns igen."
                : $"Klassificeras med {string.Join(" och ", models)}.";
        }
    }

    public override void OnActivated()
    {
        ClientNames = _timesheets.GetClients().Select(c => c.Name).Append(TimesheetBuilder.InternalLabel).ToList();
        OnPropertyChanged(nameof(ClientNames));
        OnPropertyChanged(nameof(Activities));
        OnPropertyChanged(nameof(ModelStatus));
        RefreshPreview();
    }

    /// <summary>Called after each sample and when classifications change, while the page is shown.</summary>
    public void OnActivityChanged()
    {
        if (Day.IsToday)
        {
            RefreshPreview();
        }
    }

    [RelayCommand(CanExecute = nameof(CanGenerate))]
    private async Task GenerateAsync()
    {
        IsGenerating = true;
        Error = null;
        Progress = 0;
        ProgressText = "Läser dagens aktivitet";
        _generation = new CancellationTokenSource();
        var token = _generation.Token;
        var date = Day.Day;

        try
        {
            var settings = _settings();
            var evidence = Evidence.Gather(_activity, Day.StartUtc, Day.EndUtc);
            var clients = _timesheets.GetClients();
            var builder = new TimesheetBuilder(
                settings.ToTimesheetOptions(),
                settings.CreateDecisionModel(_http),
                settings.CreateLanguageModel(_http),
                _labels);

            var progress = new Progress<TimesheetProgress>(p =>
            {
                Progress = p.Total == 0 ? 0 : 100.0 * p.Done / p.Total;
                ProgressText = p.Total == 0 ? p.Message : $"{p.Message} ({p.Done} av {p.Total})";
            });
            var entries = await Task.Run(() => builder.BuildAsync(date, evidence, clients, progress, token), token);

            _timesheets.ReplaceEntries(date, entries);
            if (Day.Day == date)
            {
                Load();
            }
        }
        catch (OperationCanceledException) when (token.IsCancellationRequested)
        {
        }
        catch (Exception ex)
        {
            // This is the boundary to the UI: show the problem rather than crash the tracker.
            Error = ex is AiServiceException or HttpRequestException ? ex.Message : $"Något gick fel: {ex.Message}";
        }
        finally
        {
            _generation.Dispose();
            _generation = null;
            IsGenerating = false;
        }
    }

    [RelayCommand]
    private void Cancel() => _generation?.Cancel();

    [RelayCommand]
    private void AddEntry()
    {
        var entry = new TimesheetEntry
        {
            Date = Day.Day,
            Client = "",
            Activity = _settings().DefaultActivity,
            Minutes = _settings().RoundingMinutes,
        };
        _timesheets.SaveEntry(entry);
        Entries.Add(Wrap(entry));
    }

    [RelayCommand]
    private void DeleteEntry(TimesheetEntryViewModel entry)
    {
        _timesheets.DeleteEntry(entry.Entry.Id);
        Entries.Remove(entry);
    }

    [RelayCommand]
    private void DismissError() => Error = null;

    /// <summary>Tab-separated rows (client, activity, hours, comment) that paste into spreadsheets and most time systems.</summary>
    public string BuildClipboardText()
    {
        var text = new StringBuilder();
        foreach (var entry in Entries.Where(e => e.Client != TimesheetBuilder.InternalLabel))
        {
            text.AppendLine(string.Join('\t', entry.Client, entry.Activity, Format.Hours(entry.Hours ?? 0), entry.Comment));
        }

        return text.ToString();
    }

    public async Task ShowCopiedAsync()
    {
        JustCopied = true;
        await Task.Delay(TimeSpan.FromSeconds(2));
        JustCopied = false;
    }

    partial void OnErrorChanged(string? value) => OnPropertyChanged(nameof(HasError));

    private bool CanGenerate() => !IsGenerating;

    private void OnDayChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(DaySelection.Date))
        {
            Error = null;
            Load();
        }
    }

    private void Load()
    {
        Entries.Clear();
        foreach (var entry in _timesheets.GetEntries(Day.Day))
        {
            Entries.Add(Wrap(entry));
        }

        RefreshPreview();
    }

    /// <summary>
    /// Rebuilds the preliminary timesheet from what is already classified. No model is asked, so
    /// this is cheap enough to run after every sample.
    /// </summary>
    private void RefreshPreview()
    {
        var settings = _settings();
        var options = settings.ToTimesheetOptions();
        var preview = new TimesheetBuilder(options, null, null, _labels)
            .Preview(Evidence.Gather(_activity, Day.StartUtc, Day.EndUtc), _timesheets.GetClients());

        Preview = preview
            .Select(p => new PreviewRow(
                p.Client,
                $"{Format.Hours(p.Minutes / 60m)} h",
                Format.Duration(p.TimeSpent),
                p.Summary,
                p.Client is not (TimesheetBuilder.UnclassifiedLabel or TimesheetBuilder.NotWorkLabel)
                    && p.Confidence < options.ConfidenceThreshold,
                p.Client is TimesheetBuilder.UnclassifiedLabel or TimesheetBuilder.NotWorkLabel))
            .ToList();

        var clientMinutes = preview
            .Where(p => p.Client is not (TimesheetBuilder.InternalLabel or TimesheetBuilder.NotWorkLabel))
            .Sum(p => p.Minutes);
        PreviewTotal = $"{Format.Hours(clientMinutes / 60m)} h";

        // A draft made earlier in the day misses what has happened since.
        var missing = TimeSpan.FromMinutes(
            preview.Where(p => p.Client != TimesheetBuilder.NotWorkLabel).Sum(p => p.Minutes) - Entries.Sum(e => e.Entry.Minutes));
        NewTime = HasEntries && Day.IsToday && missing.TotalMinutes >= options.RoundingMinutes
            ? Format.Duration(missing)
            : null;
    }

    private TimesheetEntryViewModel Wrap(TimesheetEntry entry) =>
        new(entry, _settings().ConfidenceThreshold, Save);

    private void Save(TimesheetEntryViewModel entry)
    {
        _timesheets.SaveEntry(entry.Entry);
        UpdateTotal();
    }

    private void OnEntriesChanged()
    {
        OnPropertyChanged(nameof(HasEntries));
        OnPropertyChanged(nameof(ShowEmptyState));
        OnPropertyChanged(nameof(ShowPreview));
        UpdateTotal();
    }

    private void UpdateTotal() =>
        Total = $"{Format.Hours(Entries.Where(e => e.Client != TimesheetBuilder.InternalLabel).Sum(e => e.Hours ?? 0))} h";
}
